### ISSUE TITLE
Getting Exception  Key XXXX has no acceptable encryption key.

### ISSUE THREAD

**Issue by Keshav2107** [vanitasvitae/pgpainless#463]
**Describe the bug**
I am getting below error when i am trying to encrypt the file 
Exception in thread "main" org.pgpainless.exception.KeyException$UnacceptableEncryptionKeyException: Key XXXX  has no acceptable encryption key.
This is happening with our customer key but when i generate the key and use the same it works fine. 

**Version**

- `pgpainless-core : 1.7.2`:
- `pgpainless-sop`:

**To Reproduce**

``` return ProducerOptions.signAndEncrypt(
                **new EncryptionOptions().addRecipient(receiverKeyRing),** - This is where the issue is happening 
                SigningOptions.get().addInlineSignature(StringUtils.isBlank(passPhrase)?SecretKeyRingProtector.unprotectedKeys():
                                SecretKeyRingProtector.unlockAnyKeyWith(Passphrase.fromPassword(passPhrase)),
                        secretKeyRing
                )
        );
Example Code Block with your Code
```

**Expected behavior**

**Additional context**

**Comment by vanitasvitae** [comment]
You are likely running into a policy issue. PGPainless refuses to use weak / outdated keys by default, so you might need to

a) fix the key (which is the best solution, but may not be easy when working with an external customer, still you might give it a go and just tell them their key is suboptimal and they should fix it), or
b) Adjust PGPainless' policy (see https://pgpainless.readthedocs.io/en/latest/quickstart.html#weak-keys-and-broken-algorithms ) to accept keys with legacy algorithms.

**Comment by Keshav2107** [comment]
Thank you for the quick and much-appreciated response.
I selected option B and found that the algorithm is set to  1 (RSA) with a key length of 2048 bits.
I added the following code, but it still isn't working. 
Do you have any other suggestions

  Map<PublicKeyAlgorithm, Integer> algorithms = new HashMap<>();
        algorithms.put(PublicKeyAlgorithm.RSA_GENERAL, 1024);
        algorithms.put(PublicKeyAlgorithm.RSA_GENERAL, 2048);
        Policy.PublicKeyAlgorithmPolicy pkPolicy =
                new Policy.PublicKeyAlgorithmPolicy(algorithms);
        PGPainless.getPolicy().setPublicKeyAlgorithmPolicy(pkPolicy);

**Comment by vanitasvitae** [comment]
It is sufficient to put() once, since this is a map with minimal bit strengths, so either `put(RSA_GENERAL, 1024)` or `put(RSA_GENERAL, 2048)`.

Further, some old keys have self-signatures made using weak hash algorithms, so this is another thing to check. PGPainless rejects recently made signatures using SHA-1 for instance, which can also be changed by modifying the policy.

**Comment by Keshav2107** [comment]
Thanks for the suggestion but in the key we have SHA-256 has algorithm and modified the policy and still got the same
Exception in thread "main" org.pgpainless.exception.KeyException$UnacceptableEncryptionKeyException: Key XXX has no acceptable encryption key.
	at org.pgpainless.encryption_signing.EncryptionOptions.addAsRecipient(EncryptionOptions.kt:201)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.kt:161)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.kt:126) 

Any additional suggestions would be greatly appreciated.

**Comment by vanitasvitae** [comment]
Are you comfortable sharing the public key with me, so I can have a look? Drop me an email at `vanitasvitae@fsfe.org`. Debugging OpenPGP keys is always a bit of a black-box problem :D

Alternatively, you could check the key using a linter such as   `sq cert lint --cert-file pubkey.asc`.

**Comment by Keshav2107** [comment]
Since this is a customer key, I’m unable to share it. However, during my debugging, I found that this key does not have the appropriate keyFlags.
 On the other hand, when I use the `gpg --encrypt test.txt `command, it works as expected.

**Comment by vanitasvitae** [comment]
Yeah, GnuPG is strange and does not follow the spec in some cases.

In this case, you can call
```java
encryptionOptions.setAllowEncryptionWithMissingKeyFlags();
```

to allow encryption for keys with missing key flags.

**Comment by Keshav2107** [comment]
Thank you very much! It’s working perfectly now, and I truly appreciate your help.

**Comment by vanitasvitae** [comment]
Glad I could help :)
